package  com.hbe.ms.common.vo;

public enum DHSID {
	// I551DOCUMENTID
	IMG_DOC_TYP_1,
	// I20DOCUMENTID
	IMG_DOC_TYP_2,
	// I327DOCUMENTID
	IMG_DOC_TYP_3,
	// I571DOCUMENTID
	IMG_DOC_TYP_4,
//	IMG_DOC_TYP_5("I551DOCUMENTID"),efferive End dated in Ref DB
	// DS2019DOCUMENTID
	IMG_DOC_TYP_6,
	// OTHERCASE1DOCUMENTID
	IMG_DOC_TYP_7,
	// I766DOCUMENTID
	IMG_DOC_TYP_8,
	// TEMPI551DOCUMENTID
	IMG_DOC_TYP_9,
	// I94DOCUMENTID
	IMG_DOC_TYP_10,
	// MACREADI551DOCUMENTID
	IMG_DOC_TYP_11;
	
}